services:
    app:
        container_name: java_blog_app
        build:
            context: .
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/blog
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres
            SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
            SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
            SPRING_JPA_HIBERNATE_DDL_AUTO: update
        depends_on:
            - db
        volumes:
            - .:/app:delegated

    db:
        container_name: java_blog_db
        image: postgres:latest
        environment:
            POSTGRES_DB: blog
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"

